### ISSUE TITLE
Nodes failed to load

### ISSUE THREAD

**Issue by Kepler-16b** [idrirap/ComfyUI-Lora-Auto-Trigger-Words#10]
Installed with comfy manager, and restarted, but all the nodes from this are not showing in comfyUI. What should I do?
I'm using latest commit of comfyUI and everything.

**Comment by idrirap** [comment]
Strange, I will check it ASAP

**Comment by Kepler-16b** [comment]
Hey, I've also tried git clone and manual extract zip, but they all failed.

**Comment by idrirap** [comment]
I gitcloned a new comfyUI at the last version in a new venv. I only installed the manager and tried to install the custom node. And it worked fine. I wasn't able to recreate the bug.
Do you have any error logs ?
Did you reload the server and the web page after installing the custom node ?

**Comment by Kepler-16b** [comment]
I don't have any error in powershell or in comfyUI. Yes I restart server after installation. 
Could you maybe share an example workflow containing these nodes? I've heard some people have trouble getting custom nodes appeared on search bar and I would like to see if that's the case.

**Comment by Kepler-16b** [comment]
It is working now. I just do "fetch update" and update everything. Then reinstall this pack and all nodes are showing.
