### ISSUE TITLE
Override Lora Name not working

### ISSUE THREAD

**Issue by hobojoker** [idrirap/ComfyUI-Lora-Auto-Trigger-Words#12]
I've tried basically every combination I can think of to override the lora name with a string/text input and I have not been able to get it to work. Every time I get an error like this: 

Error occurred when executing LoraLoaderAdvanced:

expected str, bytes or os.PathLike object, not NoneType

File "E:\ComfyUIUpdate\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\ComfyUIUpdate\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\ComfyUIUpdate\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\ComfyUIUpdate\ComfyUI\custom_nodes\ComfyUI-Lora-Auto-Trigger-Words\nodes_autotrigger.py", line 134, in load_lora
meta_tags_list = sort_tags_by_frequency(get_metadata(lora_name["content"], "loras"))
File "E:\ComfyUIUpdate\ComfyUI\custom_nodes\ComfyUI-Lora-Auto-Trigger-Words\utils.py", line 138, in get_metadata
with open(filepath, "rb") as file:

I've tried using a primitive, a text box, a textbasicinput, as an input as well...

Inputs I've tried (a Lora that exists in my lora folder)

add-detail-xl
add-detail-xl.safetensors
"add-detail-xl"
"add-detail-xl.safetensors"

/add-detail-xl
/add-detail-xl.safetensors
"/add-detail-xl"
"/add-detail-xl.safetensors"

lora/add-detail-xl <-- I know I'm getting off into the weeds here because obviously this is wrong looking at the nodes_autotrigger.py...
lora/add-detail-xl.safetensors
"lora/add-detail-xl"
"lora/add-detail-xl.safetensors"

All of them throw the same error

**Comment by hobojoker** [comment]
Ah, I got it to work in the LoraLoaderVanilla, but it's broken in LoraLoaderAdvanced?

**Comment by idrirap** [comment]
Hello, unfortunately I won't be able to fix/investigate this properly until friday. 

Did you tried using the node "LoraListNames" as an input for the override lora name ?
(It's not well documentes, my bad). It should list and input properly the lora names and path.

And what is your use case? Are you using lora outside of your standard lora folder ? If not the node LoraListNames should work. 

If it still won't work, I won't be able to help more for now unfortunately.

**Comment by hobojoker** [comment]
> Hello, unfortunately I won't be able to fix/investigate this properly until friday.
> 
> Did you tried using the node "LoraListNames" as an input for the override lora name ? (It's not well documentes, my bad). It should list and input properly the lora names and path.
> 
> And what is your use case? Are you using lora outside of your standard lora folder ? If not the node LoraListNames should work.
> 
> If it still won't work, I won't be able to help more for now unfortunately.

Thanks for feedback, I'm trying to really figure out exactly what is going on here but struggling. I'm using lora in the comfyui lora folder, and not even in a subfolder. 

I've tried using LoraListNames as an input as well - and for some reason that also does not work. I was messing around though and I tried using it in a different part of the graph and it worked?? Looking to root cause this.


Ah - I figured it out - using override + enable_preview was causing the error

**Comment by idrirap** [comment]
It helped a lot. I found the problem and solved it (I think).
