### ISSUE TITLE
One small suggestion

### ISSUE THREAD

**Issue by laignguihua** [idrirap/ComfyUI-Lora-Auto-Trigger-Words#14]
The "LoraLoaderStackedAdvanced" node can add "view info..." to the context menu. like the "Efficient Loader" node, so we don't have to go back to the "LoraLoader|pysssss" node to find the “view info...” .

**Comment by idrirap** [comment]
I will see what I can do about it :)

**Comment by idrirap** [comment]
after a few tests it seems to work great.
