### ISSUE TITLE
Optimization suggestions

### ISSUE THREAD

**Issue by idesign2018** [idrirap/ComfyUI-Lora-Auto-Trigger-Words#15]
![image](https://github.com/idrirap/ComfyUI-Lora-Auto-Trigger-Words/assets/42263070/3e0f7821-b22c-4526-ad5a-d3f7af2ff1fc)

Is it possible to display a thumbnail like "②" when the mouse passes over the model? Now when the mouse passes over the next level of the model, the thumbnail of the model is displayed like "①". It feels a bit troublesome.

**Comment by idrirap** [comment]
Unfortunately I can't change this. The thumbnail is a feature of https://github.com/pythongosssss/ComfyUI-Custom-Scripts?tab=readme-ov-file#testing-better-loader-lists that I am using.
