### ISSUE TITLE
Another small improvement

### ISSUE THREAD

**Issue by gontz** [idrirap/ComfyUI-Lora-Auto-Trigger-Words#16]
Hello,
Love the plugin. 
Could you please add an extra output with the selected Lora name?
So that the Lora name can be used either as input for the next Lora loader or as text to be added to the rendered image

**Comment by LankyPoet** [comment]
I like this idea, especially if it could be referenced in the save file node (by using something like %LoraName.text% ) .

**Comment by idrirap** [comment]
I added the extra output as `lora_name`. It is compatible with `override_lora_name`

**Comment by idrirap** [comment]
What custom node are you using for adding text to the images ?
