### ISSUE TITLE
LoraLoaderStackedAdvanced weighting issue?

### ISSUE THREAD

**Issue by LankyPoet** [idrirap/ComfyUI-Lora-Auto-Trigger-Words#17]
Hi,
First - thank you for making this! I am really finding it helpful.

I am using LoraLoaderStackedAdvanced , then outputting civit tags list to Tags Selector, then I show text from the tags selector.

When I select a weight in LoraLoaderStackedAdvanced, the ShowText (from Tags Selector) does not show the same weighting.

Shouldn't the weight only have to be selected once and flow through?

![image](https://github.com/idrirap/ComfyUI-Lora-Auto-Trigger-Words/assets/146845805/401815c9-8369-4e01-9845-305e7337389b)

**Comment by idrirap** [comment]
Hello, I should have maybe use two different words for "weight". 

The first weight in the LoraLoader represent how much of the weight of the whole lora is going to be _injected_ in the model. It is the equivalent of the "strength_model" in the default `Load LoRA` node.

The second weight represent the weight of the individual selected tags. Like `(tag:1.2)`.
