### ISSUE TITLE
[Question] : Workflow config using Stacked Loras

### ISSUE THREAD

**Issue by ondrovic** [idrirap/ComfyUI-Lora-Auto-Trigger-Words#28]
You said it works with [Stacked Loras](https://github.com/jags111/efficiency-nodes-comfyui), any chance you have an example workflow using it?

Is it possible to use a lora stack and get the tags for each lora used?

**Comment by idrirap** [comment]
Hello, no it doesn't work that way and I don't think I can do it.
When I says it is compatible with lora stack means it behave like it and can be used as input for the efficient loader.
You can append it to other lora_stack or you can append lora stack to it. But you will only see the tags of the current lora loaded by this node. Not the other ones. If you want to see them all, you have to stack them.
![image](https://github.com/user-attachments/assets/ddab3ce3-a4c3-46e5-a8ad-e3c5bba1aa51)
![image](https://github.com/user-attachments/assets/3f9b5479-62ff-421c-94b7-a7a19a095980)
![image](https://github.com/user-attachments/assets/0bc8c244-5354-43ee-abd0-b09c68157ce2)
![image](https://github.com/user-attachments/assets/7c915b18-2d3a-4127-8c9a-14387fd21fa5)

**Comment by ondrovic** [comment]
awesome thanks that was what I was thinking but wanted to make sure.
