### ISSUE TITLE
[FR] LoraLoaderModelOnly version

### ISSUE THREAD

**Issue by DrJKL** [idrirap/ComfyUI-Lora-Auto-Trigger-Words#33]
Just a version of the node that doesn't take or modify the CLIP. Useful with FLUX LoRAs where otherwise there can be memory issues.

**Comment by DrJKL** [comment]
Yes, but the native Comfy LoraLoaderModelOnly and LoraTagsOnly can't share the same primitive for `lora_name`
![image](https://github.com/user-attachments/assets/cf97b96c-4516-4a87-aaea-d930e00d59a1)

**Comment by idrirap** [comment]
Ok I get it now. I never used LoraLoaderModelOnly and didn't even know it existed. I will try to make a new one with the tag list

**Comment by idrirap** [comment]
I made a few tests and now removing the CLIP gives it exactly the same behavior as the LoraLoaderModelOnly.
