### ISSUE TITLE
Preview images only allow png - New Civitai format is jpeg

### ISSUE THREAD

**Issue by DeepSeaCatz** [idrirap/ComfyUI-Lora-Auto-Trigger-Words#34]
Hi there, first of all I'd like to thank you for making this node pack! I am using your LoraLoaderStackedAdvanced on all of my workflows, it's so convenient to see the preview images that goes with the lora name! I'd wish there would be a Checkpoint loader that did the similar effect.

I've re-started subscribing to Civitai membership to have the Civitai Link, which download a preview image version of the model at the same time of the model. I realized that they used to automatically download the images to png on A1111, but the ComfyUI Civitai Link now downloads them all as jpeg, which the **Lora Loader** doesn't find them (See missing * next to model name):
![image](https://github.com/user-attachments/assets/c2b5ee9f-0996-4c91-ac4e-c0a4cbeb1c82)

If generating multiple times, it will keep the older lora preview image found while applying the new lora on top, which can be confusing.

My current workaround is using a Txt Replace to change it to preview.jpeg and loading the preview image in a Preview Image node:
![image](https://github.com/user-attachments/assets/94de5420-35ac-40af-a7af-19c9e73c91c9)

I am wondering if it would be possible to modify the code of the node so that it accept all type of file format after _.preview_? This way it would future proof it if there's a different image format.

Thanks!

**Comment by DeepSeaCatz** [comment]
I guess this is one way to accept most file format, which seems to work in utils.py.
![image](https://github.com/user-attachments/assets/890d413c-b75d-42a6-a283-6a2ae8ec36b3)

Not sure if we should just stick to this or go in something like `"preview.*"`

**Comment by idrirap** [comment]
It should work now :)

**Comment by idrirap** [comment]
Reopen the issue if the last update didn't fix it
