### ISSUE TITLE
Cache not clearing when switching loras

### ISSUE THREAD

**Issue by Reledia** [idrirap/ComfyUI-Lora-Auto-Trigger-Words#4]
Using the efficiency Lora Stacker and the civitai Lora Loader Stacker, the loras used seems to remain in cache even after deselecting them from the Lora Loader Stacker. This is not happening when deselecting them from the efficiency one.
The remaining loras impact future generations.

My worflow as png:
![workflow (1)](https://github.com/idrirap/ComfyUI-Lora-Auto-Trigger-Words/assets/82183718/293fd136-3fea-40cc-b138-4a30bce354dc)

Cache content during the same worflow (The Nerissa lora was used in the generation before the Frieren one):
![ksnip_20231117-173434](https://github.com/idrirap/ComfyUI-Lora-Auto-Trigger-Words/assets/82183718/252125ef-3c8a-4409-bf96-6692f1e9c3c4)

**Comment by idrirap** [comment]
looking into it :)

**Comment by idrirap** [comment]
Should be good now. Thanks for the report ! (in the end it impacted both LoraLoaderStackedAdvanced and LoraLoaderStackedVanilla)
