### ISSUE TITLE
Does this identify XL v 1.5 versions?

### ISSUE THREAD

**Issue by Duemellon** [idrirap/ComfyUI-Lora-Auto-Trigger-Words#6]
Maybe I'm missing the identifier if there is one.

**Comment by Duemellon** [comment]
In this case I'm asking:
Does the node show that the Lora is SDXL or SD1.5? & display that info that a Lora is XL or 1.5?

That can be helpful to have

**Comment by idrirap** [comment]
I am sorry I am not able to do tell the difference between both. I looked into it and from the files metadata only, there is no easy way to tell. Or none if metadata are missing. 
To easily find your sdxl models and lora, you should either add sdxl in the name or put them in a different directory when downloading them. I'm sorry there is not much more I can do about this.
